### ISSUE TITLE
question of depth_model

### ISSUE THREAD

**Issue by baekhyun77** [fudan-zvg/S-NeRF#10]
Thank you for your work. When processing data, in the 'depth_model' section, I run:
```
1. Run `python scripts/run.py`
2. The output will be saved in data/scenes/depths

```
The program encountered the following error during execution. Can you please help me identify where the issue occurred?

removed 0 old files in output folder
Save image 37/39
Save image 38/39
Save image 39/39
Save image 39/39
Traceback (most recent call last):
  File "scripts/YORO_1CAM_PIPELINE_REFINE.py", line 810, in <module>
    one_cam_process(args)
  File "scripts/YORO_1CAM_PIPELINE_REFINE.py", line 441, in one_cam_process
    msg = model.load_state_dict(torch.load(args.model)['state_dict'], strict=False)
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/root/miniconda3/envs/S-NeRF/lib/python3.8/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by FooAuto** [comment]
I also encounter the same problem and I haven't fixed it.
